eureka:
  client:
    serviceUrl:
      #      eureka的注册中心地址
      defaultZone: http://localhost:8888/eureka/
server:
  #  此项目端口号
  port: 2001
spring:
  application:
    #    注册进eureka的名字
    name: service-order
    cloud:
      sentinel:
        transport:
          dashboard: localhost:9999
